/* =====================================================================
   P6 무지개다리 전환 — 테스트케이스 정의 (리뷰 드로어 '테스트케이스' 탭)
   결과(Pass/Fail)와 항목별 코멘트는 저장소(Supabase/localStorage)에 보관되므로
   이 파일에는 검증 항목 정의만 둔다.
   ===================================================================== */
window.SPEC_TESTCASES = Object.assign(window.SPEC_TESTCASES || {}, {
  'user/rainbow-transition': [
    { id: 'TC-01', cat: '진입', title: '기본 진입 시 STEP1 노출',
      pre: '쿼리 없이 페이지 진입', steps: 'rainbow-transition.html 접속 후 화면 확인',
      expect: 'STEP1(이별일·한마디 입력, 안내 선택 토글)이 표시되고, 헤더 아래 진행 트랙의 무지개 띠가 약 1/3 채워지며 트랙 우측에 "1 / 3"이 보인다.' },
    { id: 'TC-02', cat: '검증', title: '이별일 미입력 시 다음 버튼 비활성',
      pre: 'STEP1 진입', steps: '이별일을 입력하지 않은 채 화면 확인',
      expect: '"다음" 버튼이 비활성(disabled) 상태로 유지된다.' },
    { id: 'TC-03', cat: '검증', title: '이별일 입력 시 다음 버튼 활성',
      pre: 'STEP1 진입', steps: '이별일 입력란에 날짜 선택',
      expect: '"다음" 버튼이 활성화된다.' },
    { id: 'TC-04', cat: '입력', title: '안내 선택 토글 기본값',
      pre: 'STEP1 진입', steps: '"가족에게 안내하기", "보내기 전 편지 게시하기" 토글의 초기 상태 확인',
      expect: '두 토글 모두 기본값이 꺼짐(off) 상태다.' },
    { id: 'TC-05', cat: '요약', title: 'STEP2 요약 카드 반영 - 값 입력한 경우',
      pre: '이별일·한마디 입력, 가족/편지 토글 on', steps: '"다음" 클릭',
      expect: 'STEP2 요약 카드에 입력한 이별일(한글 날짜)·한마디·"언니 은지님에게 보낼게요"·"추모관에 게시할게요"가 표시된다.' },
    { id: 'TC-06', cat: '요약', title: 'STEP2 요약 카드 반영 - 값 비운 경우',
      pre: '이별일만 입력, 한마디 공백, 토글 모두 off', steps: '"다음" 클릭',
      expect: 'STEP2 요약 카드의 한마디는 "남기지 않았어요", 가족·편지 항목은 각각 "보내지 않을게요"/"게시하지 않을게요"로 표시된다.' },
    { id: 'TC-07', cat: '내비게이션', title: 'STEP2 "잠시 후에 할게요"',
      pre: 'STEP2 진입', steps: '"잠시 후에 할게요" 클릭',
      expect: 'STEP1로 돌아가고 진행 표시가 "1 / 3"이 된다.' },
    { id: 'TC-08', cat: '내비게이션', title: 'STEP2 "네, 기록할게요"',
      pre: 'STEP2 진입', steps: '"네, 기록할게요" 클릭',
      expect: 'STEP3(최종 확인)로 이동하고 진행 트랙의 무지개 띠가 전체 폭으로 채워지며 우측 표시가 "3 / 3"이 된다.' },
    { id: 'TC-09', cat: '목록', title: 'STEP3 조건부 항목 노출 - 토글 on',
      pre: 'STEP1에서 가족 안내·편지 게시 토글 on 후 STEP3까지 진입', steps: 'STEP3 처리 예정 목록 확인',
      expect: '"언니 은지님에게 소식을 전할게요"와 "써둔 편지를 추모관에 게시할게요" 항목이 노출된다.' },
    { id: 'TC-10', cat: '목록', title: 'STEP3 조건부 항목 숨김 - 토글 off',
      pre: 'STEP1에서 두 토글 모두 off 후 STEP3까지 진입', steps: 'STEP3 처리 예정 목록 확인',
      expect: '가족·편지 관련 항목이 노출되지 않고 알림 중지·추모관 생성·홈 전환 3개 항목만 보인다.' },
    { id: 'TC-11', cat: '검증', title: '동의 체크 전 전환 완료 버튼 비활성',
      pre: 'STEP3 진입', steps: '동의 체크박스를 체크하지 않은 채 확인',
      expect: '"전환 완료하기" 버튼이 비활성 상태다.' },
    { id: 'TC-12', cat: '검증', title: '동의 체크 시 전환 완료 버튼 활성',
      pre: 'STEP3 진입', steps: '동의 체크박스 체크',
      expect: '"전환 완료하기" 버튼이 활성화된다.' },
    { id: 'TC-13', cat: '등록', title: '전환 완료 시 상태 저장 및 STEP4 이동',
      pre: 'STEP3에서 동의 체크 완료', steps: '"전환 완료하기" 클릭',
      expect: 'STEP4(전환 완료 결과)로 이동하고 반려견 상태가 무지개다리로 저장된다(개발 반영 시).' },
    { id: 'TC-14', cat: '검증', title: '되돌리기 기한 자동 계산',
      pre: '이별일을 특정 날짜로 입력 후 STEP3까지 진행 완료', steps: '전환 완료 클릭 후 STEP4의 되돌리기 안내 문구 확인',
      expect: '안내 문구의 날짜가 입력한 이별일로부터 정확히 7일 뒤 날짜로 표시된다.' },
    { id: 'TC-15', cat: '목록', title: 'STEP4 결과 목록 체크 표시',
      pre: '전환 완료 처리(STEP4 진입)', steps: 'STEP4 결과 목록 확인',
      expect: '알림 중지·추모관 생성·홈 전환(및 선택한 가족/편지 항목)에 완료 체크 아이콘이 표시된다.' },
    { id: 'TC-16', cat: '내비게이션', title: 'STEP4 CTA 링크',
      pre: 'STEP4 진입', steps: '"OO의 공간으로 가기"와 "메모리얼 페이지 바로 열기" 버튼 확인',
      expect: '전자는 home.html로, 후자는 memorial-edit.html로 이동하는 링크로 연결돼 있다.' },
    { id: 'TC-17', cat: '진입', title: '되돌리기 모드 진입 시 STEP5 직행',
      pre: '전환 완료로 상태값이 저장된 상태', steps: '"rainbow-transition.html?mode=revert" 로 접속',
      expect: 'STEP1~4를 거치지 않고 곧바로 STEP5(되돌리기 확인) 화면이 표시되며 헤더 제목이 "이전 상태로 되돌리기"로 보인다.' },
    { id: 'TC-18', cat: '상태', title: 'STEP5 되돌릴 상태 라벨 표시',
      pre: '전환 직전 상태가 저장돼 있음(예: 이별 준비)', steps: '?mode=revert 로 진입 후 요약 카드·목록 확인',
      expect: '"되돌릴 상태"와 목록의 홈 전환 문구에 저장된 직전 상태 라벨(예: 이별 준비)이 동일하게 표시된다.' },
    { id: 'TC-19', cat: '내비게이션', title: 'STEP5 "그대로 둘게요"',
      pre: 'STEP5 진입', steps: '"그대로 둘게요" 클릭',
      expect: '상태 변경 없이 home.html로 이동한다.' },
    { id: 'TC-20', cat: '등록', title: 'STEP5 "이전 상태로 되돌리기" 실행',
      pre: 'STEP5 진입', steps: '"이전 상태로 되돌리기" 클릭',
      expect: 'STEP6(되돌리기 완료)로 이동하고 반려견 상태가 직전 상태로 복원된다(개발 반영 시).' },
    { id: 'TC-21', cat: '목록', title: 'STEP6 완료 목록 및 CTA',
      pre: 'STEP5에서 되돌리기 실행 완료', steps: 'STEP6 화면 확인',
      expect: '"홈 화면을 [직전 상태] 상태로 바꿨어요"·"추모관은 비공개로 보관돼요" 항목에 체크 표시가 있고 "홈으로 가기" 버튼이 home.html로 연결된다.' },
    { id: 'TC-22', cat: '내비게이션', title: '뒤로가기 버튼 동작',
      pre: 'STEP2 또는 STEP3 진입', steps: '헤더의 뒤로가기 버튼 클릭',
      expect: '바로 이전 단계 화면으로 이동한다(STEP1 또는 STEP5에서는 home.html로 이동).' },
    { id: 'TC-23', cat: '레이아웃', title: '반려견 이름 쿼리 치환',
      pre: '없음', steps: '"rainbow-transition.html?pet=콩이" 로 접속',
      expect: 'data-pet-name으로 표기된 반려견 이름(STEP1·STEP2 안내 문구, STEP3·STEP4 추모관 항목, STEP4 제목과 "OO의 공간으로 가기" CTA, STEP5·STEP6 제목)이 "콩이"로 치환되어 표시된다.' }
  ]
});
